spring:
  application:
    name: auth-server
  config:
    import: optional:file:.env[.properties]

server:
  port: ${SERVER_PORT:9000}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
