spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: parkings
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/parkings/**
              filters:
                - RewritePath=/api/v1/parkings(?<segment>/?.*), /parkings${segment}

server:
  port: 8080
