spring:
  application:
    name: discovery
  config:
    import: optional:file:.env[.properties]

server:
  port: ${SERVER_PORT:8761}

eureka:
  client:
    register-with-eureka: false   # 자기 자신은 등록하지 않음
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
